management:
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
  # All traces should be sent to latency analysis tool
  tracing.sampling.probability: 1.0
  endpoint:
    health.enabled: true
    prometheus.enabled: true
    loggers.enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include: health,loggers,prometheus